uses:
    - django
ignore-paths:
    - deployment
    - evap/static
    - evap/static_collected
    - src
python-targets:
    - 3
test-warnings: true
doc-warnings: no
strictness: veryhigh
pep8:
  disable:
    - E501  # line too long - code formatting is done by black
    - W503  # line break before operator
    - E128  # hanging indents not allowed
    - E126  # overindentation
    - N802  # function name should be lowercase - lots of false positives in tests that pylint doesn't show
    - N803  # argument name should be lowercase - pylint has this as well (and there we tweaked it)
    - N806  # variable in function should be lowercase - lots of false positives, mostly Formset classes made from factories
    - N804  # first argument of a classmethod should be named 'cls' - one false positive and pylint does it better
    - E266  # too many leading '#' for block comment - that's used in settings on purpose
pyflakes:
  disable:
    - F999  # python >3.5 triggers this
    - E701  # type annotations trigger this.
    - F403  # pylint handles this.
    - F401  # pylint handles this.
pylint:
  run: false # we run pylint manually
dodgy:
  run: false # duplicates messages of bandit, but ignores #nosec comments. Not configurable.
